import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseAppearanceLibraryConfig, parseFishConfig, parsePlayerAppearanceConfig, parseSkillConfig, parseSkillLibraryConfig, parseSkillLoadoutConfig, parseWorldConfig } from '../assets/scripts/data/ConfigValidator.ts';

const root = fileURLToPath(new URL('..', import.meta.url));
const readJson = (name) => JSON.parse(readFileSync(join(root, 'assets', 'resources', 'configs', name), 'utf8'));

test('鱼、技能和世界样例配置可校验', () => {
  const player = parseFishConfig(readJson('fish-player.json'));
  assert.equal(player.id, 'fish-player-crucian');
  assert.equal(player.artFacingDirection, 'right');
  assert.deepEqual(player.animationArtFacingDirections, { swim: 'right', bite: 'left', hurt: 'right' });
  assert.equal(parseSkillConfig(readJson('skill-basic-bite.json')).animationState, 'bite');
  const dash = parseSkillConfig(readJson('skill-dash-bite.json'));
  assert.equal(dash.displayName, '鲫鱼抢食');
  assert.equal(dash.animationState, 'dashBite');
  assert.equal(dash.ui.slotIndex, 0);
  assert.equal(dash.clientEffect.kind, 'dashBite');
  const whale = parseSkillConfig(readJson('skill-whale-swallow.json'));
  assert.equal(whale.animationState, 'whaleSwallow');
  assert.equal(whale.damage, 0);
  assert.equal(whale.effectDurationSeconds, 3);
  assert.equal(whale.scaleMultiplier, 3);
  assert.equal(whale.opacity, 0.5);
  assert.equal(whale.ui.iconPath, 'art/ui/skill-whale-swallow');
  assert.equal(whale.clientEffect.visualRadius, 96);
  const deathRoll = parseSkillConfig(readJson('skill-placeholder-3.json'));
  assert.equal(deathRoll.id, 'skill-death-roll');
  assert.equal(deathRoll.networkSkillId, 'skill-death-roll');
  assert.equal(deathRoll.animationState, 'deathRoll');
  assert.equal(deathRoll.damage, 3);
  assert.equal(deathRoll.clientEffect.kind, 'deathRoll');
  const inkSplash = parseSkillConfig(readJson('skill-placeholder-4.json'));
  assert.equal(inkSplash.id, 'skill-ink-splash');
  assert.equal(inkSplash.networkSkillId, 'skill-ink-splash');
  assert.equal(inkSplash.animationState, 'inkSplash');
  assert.equal(inkSplash.clientEffect.kind, 'inkSplash');
  assert.equal(inkSplash.clientEffect.rayCount, 16);
  const orcaCharge = parseSkillConfig(readJson('skill-orca-charge.json'));
  assert.equal(orcaCharge.id, 'skill-orca-charge');
  assert.equal(orcaCharge.animationState, 'orcaCharge');
  assert.equal(orcaCharge.damage, 60);
  assert.equal(orcaCharge.range, 900);
  assert.equal(orcaCharge.knockbackDistance, 360);
  assert.equal(orcaCharge.targetStopDistance, 96);
  assert.equal(orcaCharge.clientEffect.kind, 'orcaCharge');
  assert.equal(orcaCharge.ui.iconPath, 'art/ui/skill-orca-charge');
  const loadout = parseSkillLoadoutConfig(readJson('skill-loadout-player.json'));
  assert.deepEqual(loadout.layout.arcAngles, [190, 155, 120, 85]);
  assert.equal(loadout.skillConfigPaths.length, 5);
  const library = parseSkillLibraryConfig(readJson('skill-library-player.json'));
  assert.equal(library.id, 'player-skill-library');
  assert.equal(library.skillConfigPaths.length, 6);
  assert.ok(loadout.skillConfigPaths.every((path) => library.skillConfigPaths.includes(path)));
  assert.ok(library.skillConfigPaths.includes('configs/skill-orca-charge'));
  const crucianAppearance = parsePlayerAppearanceConfig(readJson('appearance-crucian.json'));
  const squidAppearance = parsePlayerAppearanceConfig(readJson('appearance-giant-squid.json'));
  const appearanceLibrary = parseAppearanceLibraryConfig(readJson('appearance-library-player.json'));
  assert.equal(crucianAppearance.animationPrefixes.attack, 'bite');
  assert.equal(squidAppearance.displayName, '大王乌贼');
  assert.deepEqual(squidAppearance.animationArtFacingDirections, { swim: 'right', attack: 'right', hurt: 'right' });
  assert.equal(squidAppearance.attackFrameCount, 8);
  assert.equal(squidAppearance.swimFrameDurationSeconds, 0.16);
  assert.equal(appearanceLibrary.defaultAppearanceId, 'appearance-crucian');
  assert.deepEqual(appearanceLibrary.appearanceConfigPaths, ['configs/appearance-crucian', 'configs/appearance-giant-squid']);
  const world = parseWorldConfig(readJson('world-sea-001.json'));
  assert.equal(world.maxActiveFish, 30);
  assert.equal(world.maxFullUpdateFish, 16);
});

test('配置校验拒绝错误版本和非法数值', () => {
  assert.throws(() => parseWorldConfig({ schemaVersion: 3, id: 'bad' }), /schemaVersion/);
  assert.throws(() => parseFishConfig({ ...readJson('fish-player.json'), maxHealth: 0 }), /maxHealth/);
  assert.throws(() => parseFishConfig({ ...readJson('fish-player.json'), artFacingDirection: 'up' }), /artFacingDirection/);
  assert.throws(() => parseFishConfig({ ...readJson('fish-player.json'), animationArtFacingDirections: { swim: 'right', bite: 'up', hurt: 'right' } }), /animationArtFacingDirections\.bite/);
  assert.throws(() => parseSkillConfig({ ...readJson('skill-whale-swallow.json'), opacity: 1.5 }), /opacity/);
  assert.throws(() => parseSkillConfig({ ...readJson('skill-basic-bite.json'), ui: { ...readJson('skill-basic-bite.json').ui, slot: 'corner' } }), /ui\.slot/);
  assert.throws(() => parseSkillLoadoutConfig({ ...readJson('skill-loadout-player.json'), layout: { ...readJson('skill-loadout-player.json').layout, arcAngles: [] } }), /arcAngles/);
  assert.throws(() => parseSkillLoadoutConfig({ ...readJson('skill-loadout-player.json'), skillConfigPaths: ['configs/skill-basic-bite', 'configs/skill-basic-bite'] }), /duplicates/);
  assert.throws(() => parseSkillLibraryConfig({ ...readJson('skill-library-player.json'), skillConfigPaths: [] }), /non-empty/);
  assert.throws(() => parsePlayerAppearanceConfig({ ...readJson('appearance-giant-squid.json'), animationArtFacingDirections: { swim: 'right', attack: 'up', hurt: 'right' } }), /animationArtFacingDirections\.attack/);
  assert.throws(() => parsePlayerAppearanceConfig({ ...readJson('appearance-giant-squid.json'), swimFrameDurationSeconds: 0 }), /swimFrameDurationSeconds/);
  assert.throws(() => parseAppearanceLibraryConfig({ ...readJson('appearance-library-player.json'), appearanceConfigPaths: [] }), /non-empty/);
});
