import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const fromRoot = (...parts) => join(root, ...parts);

const requiredPaths = [
  'package.json',
  'tsconfig.json',
  'AGENTS.md',
  'README.md',
  'docs/game-design.md',
  'docs/architecture.md',
  'docs/cocos-assets.md',
  'docs/cocos-runtime-compat.md',
  'docs/enemy-behavior.md',
  'docs/level-data.md',
  'docs/pickup-settlement.md',
  'docs/physics.md',
  'docs/projectiles.md',
  'docs/result-view.md',
  'docs/runtime-restart.md',
  'assets/animations.meta',
  'assets/animations/animation-states.json',
  'assets/animations/animation-states.json.meta',
  'assets/scenes',
  'assets/scenes.meta',
  'assets/scenes/MainScene.scene',
  'assets/scenes/MainScene.scene.meta',
  'assets/resources.meta',
  'assets/resources/art.meta',
  'assets/resources/art/characters.meta',
  'assets/resources/art/enemies.meta',
  'assets/resources/art/weapons.meta',
  'assets/resources/art/pickups.meta',
  'assets/resources/art/ui.meta',
  'assets/resources/art/ui/hud-heart.svg',
  'assets/resources/art/ui/hud-heart.svg.meta',
  'assets/resources/art/ui/hud-coin.svg',
  'assets/resources/art/ui/hud-coin.svg.meta',
  'assets/resources/art/ui/hud-weapon.svg',
  'assets/resources/art/ui/hud-weapon.svg.meta',
  'assets/prefabs.meta',
  'assets/prefabs/prefab-plan.json',
  'assets/prefabs/prefab-plan.json.meta',
  'assets/prefabs/PlayerRoot.prefab',
  'assets/prefabs/PlayerRoot.prefab.meta',
  'assets/prefabs/EnemyForestSlime.prefab',
  'assets/prefabs/EnemyForestSlime.prefab.meta',
  'assets/prefabs/PlayerBullet.prefab',
  'assets/prefabs/PlayerBullet.prefab.meta',
  'assets/prefabs/CoinPickup.prefab',
  'assets/prefabs/CoinPickup.prefab.meta',
  'assets/prefabs/WeaponBoostPickup.prefab',
  'assets/prefabs/WeaponBoostPickup.prefab.meta',
  'assets/prefabs/HudRoot.prefab',
  'assets/prefabs/HudRoot.prefab.meta',
  'assets/scripts/core',
  'assets/scripts/core/GameState.js',
  'assets/scripts/core/GameState.ts',
  'assets/scripts/cocos/CocosNodeNames.js',
  'assets/scripts/cocos/CocosNodeNames.ts',
  'assets/scripts/cocos/RuntimeNodeBinder.js',
  'assets/scripts/cocos/RuntimeNodeBinder.ts',
  'assets/scripts/cocos/GameAppComponent.js',
  'assets/scripts/cocos/GameAppComponent.ts',
  'assets/scripts/cocos.meta',
  'assets/scripts/runtime',
  'assets/scripts/runtime/GameRuntime.js',
  'assets/scripts/runtime/GameRuntime.ts',
  'assets/scripts/runtime/InputAdapter.js',
  'assets/scripts/runtime/InputAdapter.ts',
  'assets/scripts/runtime/RuntimeViewModel.js',
  'assets/scripts/runtime/RuntimeViewModel.ts',
  'assets/scripts/platform',
  'assets/scripts/data',
  'assets/scripts/data/LevelData.js',
  'assets/scripts/data/LevelData.ts',
  'assets/scripts/ui',
  'assets/scripts/audio',
  'assets/scripts/shared',
  'assets/resources/configs',
  'tests/project-structure.test.mjs',
  'tests/core-gameplay.test.mjs',
  'tests/runtime-connection.test.mjs',
  'tests/runtime-result-view.test.mjs',
  'tests/runtime-restart.test.mjs',
  'tests/cocos-bridge.test.mjs',
  'tests/cocos-scene-assets.test.mjs',
  'tests/cocos-prefabs.test.mjs',
  'tests/cocos-runtime-compat.test.mjs',
  'tests/enemy-behavior.test.mjs',
  'tests/art-animation-assets.test.mjs',
  'tests/level-data.test.mjs',
  'tests/physics-collision.test.mjs',
  'tests/pickup-settlement.test.mjs',
  'tests/projectile-combat.test.mjs'
];

const missing = requiredPaths.filter((path) => !existsSync(fromRoot(path)));
assert.deepEqual(missing, [], `缺少工程骨架路径：${missing.join(', ')}`);

for (const configName of ['player.json', 'weapon-basic.json', 'enemy-slime.json', 'level-001.json']) {
  JSON.parse(readFileSync(fromRoot('assets/resources/configs', configName), 'utf8'));
}

console.log('HeroBattleBeasts 工程骨架检查通过。');
